# Generated by Django 5.0.6 on 2024-06-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
