# Generated by Django 5.0.6 on 2024-06-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
